application:
  chart_path: deploy
  secret_name: secret
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  value_overrides:
    application:
      deployment:
        image:
          repository: {{APPLICATION_IMAGE_NAME}}
          tag: {{APPLICATION_IMAGE_TAG}}
  
