application:
  chart_path: deploy
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: alpha
  value_overrides:
    application:
      deployment:
        image:
          repository: {{APPLICATION_IMAGE_NAME}}
          tag: {{APPLICATION_IMAGE_TAG}}
