package com.stakater.nordmart;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.stakater.nordmart.service.ReviewServiceImpl;
import feign.RequestInterceptor;
import feign.RequestTemplate;
import io.jaegertracing.Configuration;
import io.opentracing.Tracer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.feign.EnableFeignClients;
import org.springframework.context.annotation.Bean;

import java.io.IOException;
import java.util.HashMap;


@SpringBootApplication
public class ReviewServiceApplication
{
    @Bean
    public Tracer jaegerTracer() {
        // The following environment variables need to set
        // JAEGER_ENDPOINT="http://10.42.126.171:28019/api/traces"
        // JAEGER_PROPAGATION="b3"
        // JAEGER_TRACEID_128BIT="true" Use 128bit tracer id to be compatible with the
        // trace id generated by istio/envoy
        return Configuration.fromEnv("nordmart-review-opentracing").getTracer();
    }

    public static void main(String[] args) {
        SpringApplication.run(ReviewServiceApplication.class, args);
    }
}
